spring:
  data:
    mongodb:
      uri: mongodb+srv://GaganiSenarathne:ABC123@clusterfuel.m6veziy.mongodb.net/?retryWrites=true&w=majority
      database: FuelApp
      
      
server:
  port: 8080

kafka:
    bootstrap-servers: 9092
    